using Zoo.Domain.Animals;

namespace Zoo.Domain.Visitors;

/// <summary>
/// Estimates how many visitor groups one exposed animal attracts
/// </summary>
public sealed class VisitorFlow
{
    /// <summary>
    /// Returns the visitor flow generated by one animal
    /// </summary>
    public decimal GetVisitorsPerAnimal(SpeciesType species, bool isHighSeason, Random? random = null)
    {
        var baseline = species switch
        {
            SpeciesType.Tiger => isHighSeason ? 30m : 5m,
            SpeciesType.Rooster => isHighSeason ? 2m : 0.5m,
            SpeciesType.Eagle => isHighSeason ? 15m : 7m,
            _ => 0m
        };

        // A small random range keeps the revenue less predictable
        if (baseline == 0m)
            return 0m;

        var source = random ?? Random.Shared;
        var multiplier = 0.8m + ((decimal)source.NextDouble() * 0.4m);

        // The multiplier keeps the variation inside the 80% to 120% range
        return baseline * multiplier;
    }
}
