namespace Zoo.Domain.Visitors;

/// <summary>
/// Stores the ticket prices used for visitor revenue
/// </summary>
public sealed class VisitorPricing
{
    public const decimal AdultTicketPrice = 17m;
    public const decimal ChildTicketPrice = 13m;

    /// <summary>
    /// Revenue generated by the default visitor group
    /// </summary>
    public decimal GroupRevenue => (2 * AdultTicketPrice) + (2 * ChildTicketPrice);
}
